#!/usr/bin/env bash

set -euo pipefail

changed_extensions=()
for file in "$@"; do
    if [[ $file == buildkit/* ]]; then
        changed_extensions+=("$(basename "$file" .yaml)")
    fi
done

printf -v regexp '|%s' "${changed_extensions[@]}"
echo "${regexp:1}"
