#!/usr/bin/env bash

set -euo pipefail

_dirs=$(find "$*" -maxdepth 3 -mindepth 3 -type d -exec realpath --relative-to="$*" {} \;)
for _dir in $_dirs; do
    _ext=$(echo "$_dir" | cut -d'/' -f1)
    _codename=$(echo "$_dir" | cut -d'/' -f2- | sed -r 's/\//:/g')

    echo "Uploading deb packages for extension $_ext for $_codename"
    deb-s3 upload \
        --lock \
        --bucket "$AWS_DEBIAN_S3_BUCKET" \
        --codename "$_codename" \
        --visibility public \
        --sign "$GPG_SIGNING_KEY_ID" \
        "$*/$_dir/*.deb"
done
