#!/usr/bin/env bash

set -euo pipefail

_dirs=$(find "$*" -maxdepth 2 -mindepth 2 -type d -exec realpath --relative-to="$*" {} \;)
for _dir in $_dirs; do
    _prefix=$(echo "$_dir" | cut -d'/' -f1)
    _codename=$(echo "$_dir" | cut -d'/' -f2)

    echo "Uploading deb packages for $_prefix:$_codename"
    deb-s3 upload \
        --lock \
        --bucket "$AWS_DEBIAN_S3_BUCKET" \
        --prefix "$_prefix" \
        --codename "$_codename" \
        --visibility public \
        --suite "$_codename" \
        --component main \
        --sign "$GPG_SIGNING_KEY_ID" \
        --preserve_versions \
        "$*/$_dir/*.deb"
done
