#!/usr/bin/env bash

set -euo pipefail

buildkit=$(find buildkit -name '*.yaml' | sed -r 's/buildkit\/(.+)\.yaml/\1/g')
arr=("$buildkit")

# shellcheck disable=SC2068
result=$(jq -nc '[ $ARGS.positional[] ]' --args ${arr[@]})

if [ $# -eq 0 ]; then
    echo "$result"
else
    echo "$result" | jq -rcM "[.[] | select(.|test(\"^($1)\$\"))]"
fi
