#!/usr/bin/env ruby

Dir["#{ARGV[0]}/**/*.deb"].map do |f|
  # filename in the format of postgresql-13-pgxman-pg-bm25_0.3.12_arm64.deb
  match = f.match(/pgxman-(.*?)_/)
  match[1] if match
end.uniq.compact.map do |f|
  f.gsub(/-/, "_")
end.each do |f|
  puts "Publishing #{f} to registry..."

  buildkit = "#{ARGV[1]}/buildkit/#{f}.yaml"
  puts %x[pgxman publish #{buildkit} --latest --registry #{ENV["PGXMAN_REGISTRY_URL"]}]
  raise "Failed to publish #{buildkit}" unless $?.success?
end
